export const dataUrl = "./data/gallery-data.json";

export const bookChapters = [
  {
    id: "invocacion-umbral",
    label: "Invocacion",
    unitId: "invocacion",
    unitLabel: "Invocacion",
    summary: "Una entrada serena para abrir el tono del libro y dejar que la memoria encuentre su luz.",
    tone: "ember",
  },
  {
    id: "invocacion-galeria",
    label: "Invocacion",
    unitId: "invocacion",
    unitLabel: "Invocacion",
    summary: "Una segunda apertura donde la memoria ya empieza a mostrarse en imagenes y pequenas notas.",
    tone: "ember",
  },
  {
    id: "invocacion-laminas",
    label: "Invocacion",
    unitId: "invocacion",
    unitLabel: "Invocacion",
    summary: "Una lamina visual para dejar que el afecto se muestre entero, sin recortes ni apuro.",
    tone: "ember",
  },
  {
    id: "latidos-pulsos",
    label: "Latidos",
    unitId: "latidos",
    unitLabel: "Latidos",
    summary: "Escenas breves que enlazan una emocion con otra, como si el libro respirara despacio.",
    tone: "rose",
  },
  {
    id: "latidos-deriva",
    label: "Latidos",
    unitId: "latidos",
    unitLabel: "Latidos",
    summary: "Una continuacion mas liviana para que el recorrido siga fluyendo sin apilarse en una sola hoja.",
    tone: "rose",
  },
  {
    id: "latidos-laminas",
    label: "Latidos",
    unitId: "latidos",
    unitLabel: "Latidos",
    summary: "Dos pausas visuales para que el amor y la cercania ocupen pagina completa.",
    tone: "rose",
  },
  {
    id: "herbario",
    label: "Herbario",
    unitId: "herbario",
    unitLabel: "Herbario",
    summary: "Un interludio botanico para sostener la atmosfera del libro entre bosque, tulipanes y calma.",
    tone: "forest",
  },
  {
    id: "constelacion-indice",
    label: "Constelacion",
    unitId: "constelacion",
    unitLabel: "Constelacion",
    summary: "Un indice vivo para volver a cada escena sin romper la delicadeza del conjunto.",
    tone: "ember",
  },
  {
    id: "constelacion-catalogo",
    label: "Constelacion",
    unitId: "constelacion",
    unitLabel: "Constelacion",
    summary: "Una segunda hoja para desplegar los capitulos sin forzar el aire de la composicion.",
    tone: "ember",
  },
  {
    id: "constelacion-catalogo-final",
    label: "Constelacion",
    unitId: "constelacion",
    unitLabel: "Constelacion",
    summary: "Una ultima hoja de catalogo para que cada bloque conserve su respiro.",
    tone: "ember",
  },
  {
    id: "constelacion-laminas",
    label: "Constelacion",
    unitId: "constelacion",
    unitLabel: "Constelacion",
    summary: "Laminas completas para que algunos recuerdos se sostengan por imagen antes del cierre.",
    tone: "ember",
  },
  {
    id: "constelacion-diptico",
    label: "Constelacion",
    unitId: "constelacion",
    unitLabel: "Constelacion",
    summary: "Un diptico visual conectado, para que dos mitades formen una sola idea sobre la pagina.",
    tone: "ember",
  },
  {
    id: "archivo-colofon",
    label: "Archivo",
    unitId: "archivo",
    unitLabel: "Archivo",
    summary: "Una ultima sala para hojearlo entero como si cada recuerdo ocupara un punto del mapa.",
    tone: "forest",
  },
  {
    id: "archivo-plancha",
    label: "Archivo",
    unitId: "archivo",
    unitLabel: "Archivo",
    summary: "Una plancha final mas abierta, para que los recuerdos descansen mejor sobre la pagina.",
    tone: "forest",
  },
  {
    id: "archivo-ponyo",
    label: "Archivo",
    unitId: "archivo",
    unitLabel: "Archivo",
    summary: "Una ultima pausa visual, suave y luminosa, para dejar dos imagenes completas al final del recorrido.",
    tone: "forest",
  },
];
