export const elements = {
  bookCover: document.querySelector("#book-cover"),
  bookShell: document.querySelector("#book-shell"),
  bookPageTitle: document.querySelector("#book-page-title"),
  bookPageIndex: document.querySelector("#book-page-index"),
  bookPageSummary: document.querySelector("#book-page-summary"),
  bookTabs: document.querySelector("#book-tabs"),
  bookPrev: document.querySelector("#book-prev"),
  bookNext: document.querySelector("#book-next"),
  bookTurn: document.querySelector("#book-turn"),
  openNextPage: document.querySelector("#open-next-page"),
  heroStack: document.querySelector("#hero-stack"),
  storyStrip: document.querySelector("#story-strip"),
  memoryGrid: document.querySelector("#memory-grid"),
  albumsGrid: document.querySelector("#albums-grid"),
  tocPreview: document.querySelector("#toc-preview"),
  archiveStats: document.querySelector("#archive-stats"),
  bookGeneratedAt: document.querySelector("#book-generated-at"),
  lightbox: document.querySelector("#lightbox"),
  lightboxImage: document.querySelector("#lightbox-image"),
  lightboxMeta: document.querySelector("#lightbox-meta"),
  lightboxTitle: document.querySelector("#lightbox-title"),
  prevShot: document.querySelector("#prev-shot"),
  nextShot: document.querySelector("#next-shot"),
  albumTemplate: document.querySelector("#album-card-template"),
};
